version: '3.3'
services:
    db:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: spug
            MYSQL_USER: spug
            MYSQL_PASSWORD: spug.dev
    web:
        depends_on:
            - db
        build: .
        container_name: spug
        restart: always
        environment:
            NAME: spug
            USER: spug
            PASSWORD: spug.dev
            HOST: db
            PORT: 3306

